version: '3.8'

services:
  backend:
    build:
      context: ./saas-it-inventory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/it_inventory
      - JWT_SECRET=${JWT_SECRET:-defaultsecret}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-defaultencryptionkey}
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: >
      sh -c "
        echo 'Starting backend service...' &&
        echo 'Environment variables:' &&
        env &&
        echo 'Running npm install...' &&
        npm install --verbose &&
        echo 'Starting server...' &&
        node server.js
      "

  frontend:
    build:
      context: ./saas-it-inventory-frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:3000/api
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: >
      sh -c "
        echo 'Starting frontend service...' &&
        echo 'Environment variables:' &&
        env &&
        echo 'Nginx configuration:' &&
        cat /etc/nginx/nginx.conf &&
        echo 'Starting Nginx...' &&
        nginx -g 'daemon off;'
      "

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: >
      sh -c "
        echo 'Starting MongoDB service...' &&
        mongod --logpath /var/log/mongodb/mongod.log --logappend
      "

volumes:
  mongo-data:
