version: '3.8'

services:
  backend:
    build: ./saas-it-inventory
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/it_inventory
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NODE_ENV=production
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./saas-it-inventory-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo-data:
