version: '3'
services:
  frontend:
    build: ./saas-it-inventory-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./saas-it-inventory
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/it_inventory
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
