version: '3.8'

services:
  frontend:
    build: ./saas-it-inventory-frontend
    ports:
      - "0.0.0.0:${FRONTEND_PORT:-80}:8080"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3000/api

  backend:
    build: ./saas-it-inventory
    ports:
      - "0.0.0.0:${BACKEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/it_inventory}
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network
    command: >
      sh -c "node scripts/init.js &&
             npm start"

  mongo:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
