version: '3.8'

services:
  frontend:
    build: ./saas-it-inventory-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./saas-it-inventory-frontend/nginx-logs:/var/log/nginx
    environment:
      - NODE_ENV=production

  backend:
    build: ./saas-it-inventory
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/it_inventory}
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network
    command: >
      sh -c "node scripts/init.js &&
             npm start"

  mongo:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:
  nginx-logs:

networks:
  app-network:
    driver: bridge
